/* soapServer.cpp
   Generated by gSOAP 2.8.14 from MPCSoapI.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.8.14 2013-08-21 08:23:30 GMT")


extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "MPC:npRequest"))
		return soap_serve_MPC__npRequest(soap);
	if (!soap_match_tag(soap, soap->tag, "MPC:flashReguest"))
		return soap_serve_MPC__flashReguest(soap);
	if (!soap_match_tag(soap, soap->tag, "MPC:typeRequest"))
		return soap_serve_MPC__typeRequest(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_MPC__npRequest(struct soap *soap)
{	struct MPC__npRequest soap_tmp_MPC__npRequest;
	struct _MPC__npRequestResponse r_output;
	soap_default_MPC__npRequestResponse(soap, &r_output);
	soap_default_MPC__npRequest(soap, &soap_tmp_MPC__npRequest);
	soap->encodingStyle = NULL;
	if (!soap_get_MPC__npRequest(soap, &soap_tmp_MPC__npRequest, "MPC:npRequest", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = MPC__npRequest(soap, soap_tmp_MPC__npRequest.r_input, r_output);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_MPC__npRequestResponse(soap, &r_output);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_MPC__npRequestResponse(soap, &r_output, "MPC:npRequestResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_MPC__npRequestResponse(soap, &r_output, "MPC:npRequestResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_MPC__flashReguest(struct soap *soap)
{	struct MPC__flashReguest soap_tmp_MPC__flashReguest;
	struct MPC__flashReguestResponse soap_tmp_MPC__flashReguestResponse;
	soap_default_MPC__flashReguestResponse(soap, &soap_tmp_MPC__flashReguestResponse);
	soap_default_MPC__flashReguest(soap, &soap_tmp_MPC__flashReguest);
	soap->encodingStyle = NULL;
	if (!soap_get_MPC__flashReguest(soap, &soap_tmp_MPC__flashReguest, "MPC:flashReguest", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = MPC__flashReguest(soap, soap_tmp_MPC__flashReguest.start_input, soap_tmp_MPC__flashReguest.pReq, soap_tmp_MPC__flashReguestResponse.count);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_MPC__flashReguestResponse(soap, &soap_tmp_MPC__flashReguestResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_MPC__flashReguestResponse(soap, &soap_tmp_MPC__flashReguestResponse, "MPC:flashReguestResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_MPC__flashReguestResponse(soap, &soap_tmp_MPC__flashReguestResponse, "MPC:flashReguestResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_MPC__typeRequest(struct soap *soap)
{	struct MPC__typeRequest soap_tmp_MPC__typeRequest;
	struct _MPC__npRequestResponse r_output;
	soap_default_MPC__npRequestResponse(soap, &r_output);
	soap_default_MPC__typeRequest(soap, &soap_tmp_MPC__typeRequest);
	soap->encodingStyle = NULL;
	if (!soap_get_MPC__typeRequest(soap, &soap_tmp_MPC__typeRequest, "MPC:typeRequest", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = MPC__typeRequest(soap, soap_tmp_MPC__typeRequest.type, soap_tmp_MPC__typeRequest.order, r_output);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_MPC__npRequestResponse(soap, &r_output);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_MPC__npRequestResponse(soap, &r_output, "MPC:npRequestResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_MPC__npRequestResponse(soap, &r_output, "MPC:npRequestResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
